#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.53.0.0.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\gaffer_source

# environment variables
environment:
  BUILD_DIR: c:\gaffer_build
  VERSION: 0.53.0.0

# uncomment this line to enable RDP access at the start of the build
# init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# build cache to preserve files/folders between builds
# cache:
  # - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  # - projectA\libs
  # - node_modules                    # local npm modules
  # - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  # - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - if not exist %BUILD_DIR% mkdir %BUILD_DIR%
  - cd %BUILD_DIR%
  - appveyor DownloadFile https://github.com/hypothetical-inc/gafferDependencies/releases/download/%VERSION%/gafferDependencies-%VERSION%-windows.zip
  - 7z x gafferDependencies-%VERSION%-windows.zip -aoa -y
  - cd %APPVEYOR_BUILD_FOLDER%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - call contrib\cmake\buildGafferWindows.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - 7z a gaffer-%VERSION%-windows.zip %BUILD_DIR%

  # to run script as a PowerShell command prepend it with ps:
  # - ps: Write-Host 'This is PowerShell'

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
# before_package:

# the install step takes care of everything since we're using cmake
build: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: gaffer-%VERSION%-windows.zip
#   # pushing a single file
#   - path: test.zip

#   # pushing a single file with environment variable in path and "Deployment name" specified
#   - path: MyProject\bin\$(configuration)
#     name: myapp

#   # pushing entire folder as a zip archive
#   - path: logs

#   # pushing all *.nupkg files in build directory recursively
#   - path: '**\*.nupkg'

